### ISSUE TITLE
Not compatibe with 1.19 (22w13a)

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [Dalarion/Stemaria#2]
hello

Minecraft : fabric-loader-0.13.3-22w13a

Stemaria-1.2.1 | MC-1.19 Experimental 1 | Croparia-3.8.3+]

As I assume that you TEST your mod before providing

I please you to provide a link to 
croparia": ">=3.8.3 , which is working on 1.19

NOTE: 1.18.2 is NOT compatible to 1.19 Snapshot (22w1xa)

regards

**Comment by Dalarion** [comment]
Stemaria-1.2.1 | MC-**1.19 Experimental 1** | Croparia-3.8.3+ is made for the **1.19 Experimental 1** version of minecraft, not 22w13a...
